modules/activity_log/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes ActivityLog
|--------------------------------------------------------------------------
|
*/

Route::group(['namespace' => 'Zent\ActivityLog\Http\Controllers', 'middleware' => ['locale']], function () {

    /**
     * Group route admin.
     */
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('activity_log', 'ActivityLogController');

        Route::prefix('activity_log')->group(function () {
            Route::post('get_list_activity_log', 'ActivityLogController@getListActivityLog')->name('activity_log.getListActivityLog');
        });
    });

    /**
     * Group route customer.
     */
    Route::group(['prefix' => 'home'], function () {
        Route::get('activity_log', 'ActivityLogController@home')->name('activityLog.home');
    });

});

modules/activity_log/resources/views/backend/create.blade.php
@extends('layout::backend.master')

@section('breadcrumb')
    <a class="breadcrumb-item" href="{{ route('activity_log.index') }}">{{ $display_name }}</a>
    <a class="breadcrumb-item active" href="{{ route('activity_log.create') }}">@lang('global.add')</a>
@endsection

@section('content')
    <div class="br-section-wrapper">
        {{-- Bg header --}}
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-18 mg-b-10">
            <i class="fa fa-plus" aria-hidden="true"></i> &nbsp;
            @lang('global.add') {{ $display_name }}
        </h6>
        <hr> <br>

        {{-- Bg content --}}
        <form action="{{ route('activity_log.store') }}" method="post" enctype="multipart/form-data" id="frm_create_activity_log">
            @csrf
            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.name')</label>
                <input type="text" name="name" id="name" class="form-control" placeholder="@lang('global.please_enter_content')">
            </div>

            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.content')</label>
                <textarea name="content" id="content" rows="5" class="form-control" placeholder="@lang('global.please_enter_content')"></textarea>
            </div>

            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.status')</label>
                <select class="form-control" name="status" id="status">
                    <option value="1">@lang('global.show')</option>
                    <option value="0">@lang('global.hide')</option>
                </select>
            </div>

            <div class="col-sm-1 col-md-1 pd-0">
                <button type="submit" class="btn btn-info btn-block mg-b-20" id="btn-create"><i class="fa fa-floppy-o" aria-hidden="true"></i> &nbsp;@lang('global.save')</button>
            </div>
        </form>
    </div>
@endsection

@section('script')
    <script>
        $('#frm_create_activity_log').on('submit', function (event) {
            event.preventDefault();

            var form = $('#frm_create_activity_log');

            $('span[class=error]').remove();

            if (!form.valid()) {
                return false;
            }

            createActivityLog(form.serialize());
        });

        $('#frm_create_activity_log').validate({
            errorElement: "span",
            rules: {
                name: {
                    required: true
                },
                content: {
                    required: true
                }
            },
            messages: {
                name: {
                    required: Lang.get('user.please_enter_name')
                },
                content: {
                    required: Lang.get('global.please_enter_content')
                }
            },
        });

        function createActivityLog(data) {
            $.ajax({
                url: app_url + 'admin/activity_log',
                type: 'POST', // GET, POST, PUT, PATCH, DELETE,
                data: {
                    data: data
                },
                success: function (res)
                {
                    if (!res.err) {
                        toastr.success(res.msg);

                        setTimeout(function () {
                            window.location.href = app_url + 'admin/activity_log';
                        }, 2000);

                        $('#btn-create').attr("disabled", "disabled");
                    } else {
                        toastr.error(res.msg);
                    }
                }
            });
        }
    </script>
@endsection

modules/activity_log/resources/views/backend/edit.blade.php
@extends('layout::backend.master')

@section('breadcrumb')
    <a class="breadcrumb-item" href="{{ route('activity_log.index') }}">{{ $display_name }}</a>
    <a class="breadcrumb-item active" href="{{ route('activity_log.create') }}">@lang('global.edit')</a>
@endsection

@section('content')
    <div class="br-section-wrapper">
        {{-- Bg header --}}
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-18 mg-b-10">
            <i class="fa fa-edit" aria-hidden="true"></i> &nbsp;
            @lang('global.edit') {{ $display_name }}
        </h6>
        <hr> <br>

        {{-- Bg content --}}
        <form action="{{ route('activity_log.update', $activity_log->id) }}" method="post" enctype="multipart/form-data" id="frm_edit_activity_log">
            @csrf
            <input type="hidden" name="_method" value="PATCH">
            <input type="hidden" name="activity_log_id" id="activity_log_id" value="{{ $activity_log->id }}">

            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.name')</label>
                <input value="{{ $activity_log->name }}" type="text" name="name" id="name" class="form-control" placeholder="@lang('global.please_enter_content')" required="">
            </div>

            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.content')</label>
                <textarea name="content" id="content" rows="5" class="form-control" placeholder="@lang('global.please_enter_content')" required="">{{ $activity_log->content }}</textarea>
            </div>

            <div class="form-group">
                <label for="" class="tx-bold">@lang('global.status')</label>
                <select class="form-control" name="status" id="status">
                    <option value="1" @if($activity_log->status == 1) selected @endif>@lang('global.show')</option>
                    <option value="0" @if($activity_log->status == 0) selected @endif>@lang('global.hide')</option>
                </select>
            </div>

            <div class="col-sm-1 col-md-1 pd-0">
                <button type="submit" class="btn btn-info btn-block mg-b-20" id="btn-create"><i class="fa fa-floppy-o" aria-hidden="true"></i> &nbsp;@lang('global.save')</button>
            </div>
        </form>
    </div>
@endsection

@section('script')
    <script>
        $('#frm_edit_activity_log').on('submit', function (event) {
            event.preventDefault();

            var form = $('#frm_edit_activity_log');

            $('span[class=error]').remove();

            if (!form.valid()) {
                return false;
            }

            updateActivityLog(form.serialize());
        });

        $('#frm_edit_activity_log').validate({
            errorElement: "span",
            rules: {
                name: {
                    required: true
                },
                content: {
                    required: true
                }
            },
            messages: {
                name: {
                    required: Lang.get('user.please_enter_name')
                },
                content: {
                    required: Lang.get('global.please_enter_content')
                }
            },
        });

        function updateActivityLog(data) {
            $.ajax({
                url: app_url + 'admin/activity_log/' + $('#user_id').val(),
                type: 'PATCH', // GET, POST, PUT, PATCH, DELETE,
                data: {
                    data: data
                },
                success: function (res)
                {
                    if (!res.err) {
                        toastr.success(res.msg);

                        setTimeout(function () {
                            window.location.href = app_url + 'admin/activity_log';
                        }, 2000);

                        $('#btn-update').attr("disabled", "disabled");
                    } else {
                        toastr.error(res.msg);
                    }
                }
            });
        }
    </script>
@endsection

modules/activity_log/resources/views/backend/index.blade.php
@extends('layout::backend.master')

@section('breadcrumb')
    <a class="breadcrumb-item active" href="{{ route('activity_log.index') }}">{{ $display_name }}</a>
    {{-- use lang in file global --}}
@endsection

@section('content')
    <div class="br-section-wrapper">
        {{-- Bg header --}}
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-18 mg-b-10">
            <i class="fa fa-flag-o" aria-hidden="true"></i> &nbsp;
            @lang('global.list') {{ $display_name }}
        </h6>
        <hr> <br>

        <div class="rounded table-responsive">
            <table class="table table-bordered mg-b-0" id="activity_log_table">
                <thead>
                    <tr>
                        <th class="wd-5p">@lang('global.order')</th>
                        <th>@lang('global.ip')</th>
                        <th>@lang('global.user')</th>
                        {{--<th>@lang('global.userType')</th>--}}
                        <th>@lang('global.route')</th>
                        <th>@lang('global.user_agent')</th>
                        {{--<th>@lang('global.locale')</th>--}}
                        {{--<th>@lang('global.referer')</th>--}}
                        <th>@lang('global.method')</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@section('script')
    <script>
        // after create cms, you need create file js, then move all contents to it.
        // please use laravel mix to manager you js
        // webpack.mix.js

        $(document).ready(function () {

            $('#activity_log_table').DataTable({
                autoWidth: true,
                processing: true,
                serverSide: true,
                ordering: false,
                ajax: {
                    url: app_url + 'admin/activity_log/get_list_activity_log',
                    type: 'post'
                },
                searching: true,
                columns: [
                    {data: 'DT_RowIndex', className: 'tx-center', searchable: false},
                    {data: 'ipAddress', className: 'tx-center'},
                    {data: 'userId'},
                    // {data: 'userType'},
                    {data: 'route'},
                    {data: 'userAgent', className:'dt-agent tx-center'},
                    // {data: 'locale'},
                    // {data: 'referer'},
                    {data: 'methodType', className: 'tx-center'},
                ],
            });

            $('#activity_log_table').on('click', '.btn-edit', function () {
                window.location.href = app_url + 'admin/activity_log/' + $(this).data('id') + '/edit';
            });

            $('#activity_log_table').on('click', '.btn-delete', function (event) {
                event.preventDefault();

                swal({
                    title: Lang.get('global.are_you_sure_to_delete'),
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#00b297',
                    cancelButtonColor: '#d33',
                    confirmButtonText: Lang.get('global.confirm'),
                    cancelButtonText: Lang.get('global.cancle')
                }).then((result) => {
                    if (result.value) {

                        $.ajax({
                            url: app_url + 'admin/activity_log/' + $(this).data('id'),
                            type: 'DELETE',
                            dataType: "JSON",
                            data: {
                                id: $(this).data('id')
                            },
                            success: function (res)
                            {
                                if (!res.err) {
                                    toastr.success(res.msg);
                                    $('#activity_log_table').DataTable().ajax.reload();
                                } else {
                                    toastr.error(res.msg);
                                }
                            }
                        });
                    }
                });
            });
        });
    </script>
@endsection

modules/activity_log/resources/views/frontend/index.blade.php
ActivityLog Frontend